### ISSUE TITLE
Update API because of GY Accounts v2

### ISSUE THREAD

**Issue by GY-CODING** [GY-CODING/fallofthegods-data#23]
The purpose of this issue is to update Fall of the Gods Data API in order for it to be up to date with GY Accounts v2 change and the full separation of functionalities.

# Tasks
- [x] Delete deprecated endpoints.
- [x] Delete deprecated entities.
- [x] Delete deprecated functionality.

In order for this issue to be closed, all tasks should be completed.
