### ISSUE TITLE
Generate tests

### ISSUE THREAD

**Issue by GY-CODING** [GY-CODING/fallofthegods-data#7]
The purpose of this issue is to generate and test tests for the Fall of the Gods API.

# Tasks
- [ ] Define which usecases should the tests cover.
- [ ] Generate the tests.
- [ ] Test the tests.

In order for this issue to be closed, all tasks should be completed.
